import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  learnSidebar: [
    {
      type: "autogenerated",
      dirName: "learn",
    },
    {
      type: "html",
      value: "<div class='sidebar-separator'></div>",
    },
    {
      type: "doc",
      id: "resources/glossary",
    },
  ],
  useSidebar: [
    {
      type: "autogenerated",
      dirName: "protocol",
    },
  ],
  developSidebar: [
    {
      type: "autogenerated",
      dirName: "develop",
    },
    // {
    //   type: "category",
    //   label: "Cross-Rollup Development",
    //   collapsible: false,
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "xdapps",
    //     },
    //   ],
    // }
  ],
  operateSidebar: [
    {
      type: "autogenerated",
      dirName: "operate",
    },
  ],
};

export default sidebars;
