[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "src/=src",
  "test/=test",
  "core/=../core",
  "nomina/=.",
]

fs_permissions = [
  { access = "read-write", path = "./test" },
  { access = "read-write", path = "./script" },
  { access = "read", path = "./out" },
]

allow_paths = ["../core"]
gas_limit = 9223372036854775807 # prev foundry default

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

bytecode_hash = "none"
cbor_metadata = false

[fuzz]
seed = "0x6eed"

[fmt]
bracket_spacing = true
number_underscore = "thousands"
