version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  labels: []
- package-ecosystem: "npm"
  directories:
    - "/docs/website"
    - "/contracts/avs"
    - "/contracts/core"
  schedule:
    interval: "daily"
  labels: []
