version: 1

project_name: omni

builds:
  - id: halo
    main: ./halo
    binary: halo
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/omni-network/omni/lib/buildinfo.version={{.Version}}

  - id: relayer
    main: ./relayer
    binary: relayer
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/omni-network/omni/lib/buildinfo.version={{.Version}}

  - id: explorer-graphql
    main: ./explorer/graphql
    binary: /explorer/graphql
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

  - id: explorer-indexer
    main: ./explorer/indexer
    binary: explorer/indexer
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

  - id: omni
    main: ./cli/cmd/omni
    binary: omni
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - -s -w -X github.com/omni-network/omni/lib/buildinfo.version={{.Version}}

dockers:
  - ids: [halo]
    dockerfile: ./halo/Dockerfile
    image_templates:
     - omniops/halo:{{ .ShortCommit }}
     - omniops/halo:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
     - omniops/halo:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

  - ids: [relayer]
    dockerfile: ./relayer/Dockerfile
    image_templates:
     - omniops/relayer:{{ .ShortCommit }}
     - omniops/relayer:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
     - omniops/relayer:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

  - ids: [explorer-graphql]
    dockerfile: ./explorer/graphql/Dockerfile
    image_templates:
      - omniops/explorer-graphql:{{ .ShortCommit }}
      - omniops/explorer-graphql:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
      - omniops/explorer-graphql:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

  - ids: [explorer-indexer]
    dockerfile: ./explorer/indexer/Dockerfile
    image_templates:
      - omniops/explorer-indexer:{{ .ShortCommit }}
      - omniops/explorer-indexer:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
      - omniops/explorer-indexer:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  ids:
    - omni # Only create release binary artefacts for omni cli.
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
