version: 1

project_name: omni

builds:
  - id: halo
    main: ./halo
    binary: halo
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/omni-network/omni/lib/buildinfo.version={{.Tag}}

  - id: relayer
    main: ./relayer
    binary: relayer
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/omni-network/omni/lib/buildinfo.version={{.Tag}}

  - id: monitor
    main: ./monitor
    binary: monitor
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]

  - id: omni
    main: ./cli/cmd/omni
    binary: omni
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - -s -w -X github.com/omni-network/omni/lib/buildinfo.version={{.Tag}}

  - id: anvilproxy
    main: ./e2e/anvilproxy
    binary: anvilproxy
    env: [ CGO_ENABLED=0 ]
    goos: [ linux ]
    goarch: [ amd64 ]

dockers:
  - ids: [halo]
    dockerfile: ./halo/Dockerfile
    image_templates:
     - omniops/halo:{{ .ShortCommit }}
     - omniops/halo:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
     - omniops/halo:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

  - ids: [relayer]
    dockerfile: ./relayer/Dockerfile
    image_templates:
     - omniops/relayer:{{ .ShortCommit }}
     - omniops/relayer:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
     - omniops/relayer:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

  - ids: [monitor]
    dockerfile: ./monitor/Dockerfile
    image_templates:
     - omniops/monitor:{{ .ShortCommit }}
     - omniops/monitor:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
     - omniops/monitor:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

  - ids: [anvilproxy]
    dockerfile: ./e2e/anvilproxy/Dockerfile
    image_templates:
     - omniops/anvilproxy:{{ .ShortCommit }}
     - omniops/anvilproxy:{{ if .IsSnapshot }}main{{ else }}latest{{ end }}
     - omniops/anvilproxy:{{ if .IsSnapshot }}main{{ else }}{{.Tag}}{{ end }}

archives:
  - format: tar.gz
    allow_different_binary_count: true # Required since anvilproxy only has linux-amd64
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
