version: 1

project_name: omni

builds:
  - id: halo
    main: ./halo
    binary: halo
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]

  - id: relayer
    main: ./relayer
    binary: relayer
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]

  - id: explorer-api
    main: ./explorer/api
    binary: /explorer/api
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

  - id: explorer-graphql
    main: ./explorer/graphql
    binary: /explorer/graphql
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

  - id: explorer-indexer
    main: ./explorer/indexer
    binary: explorer/indexer
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

dockers:
  - ids: [halo]
    dockerfile: ./halo/Dockerfile
    image_templates:
     - omniops/halo:latest

  - ids: [relayer]
    dockerfile: ./relayer/Dockerfile
    image_templates:
     - omniops/relayer:latest

  - ids: [explorer-api]
    dockerfile: ./explorer/api/Dockerfile
    image_templates:
      - omniops/explorer-api:latest

  - ids: [explorer-graphql]
    dockerfile: ./explorer/graphql/Dockerfile
    image_templates:
      - omniops/explorer-graphql:latest

  - ids: [explorer-indexer]
    dockerfile: ./explorer/indexer/Dockerfile
    image_templates:
      - omniops/explorer-indexer:latest

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
