[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "src/=src",
  "core-test/=../core/test",
  "core/=../core/src",
  "test/=test",
  # required so that imports in core/ can be resolved
  "avs/=src",
  # remapping for eigenlayers import
  '@openzeppelin-upgrades/contracts/=node_modules/@openzeppelin/contracts-upgradeable',
]

fs_permissions = [
  { access = "read-write", path = "./script" },
]

allow_paths = ["../core"]

solc_version = "0.8.12"
optimizer = true
optimizer_runs = 200

[fuzz]
seed = "0x6eed"

[fmt]
bracket_spacing = true
number_underscore = "thousands"
