// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omni-network/omni/explorer/db/ent/block"
	"github.com/omni-network/omni/explorer/db/ent/msg"
	"github.com/omni-network/omni/explorer/db/ent/predicate"
	"github.com/omni-network/omni/explorer/db/ent/receipt"
)

// BlockUpdate is the builder for updating Block entities.
type BlockUpdate struct {
	config
	hooks    []Hook
	mutation *BlockMutation
}

// Where appends a list predicates to the BlockUpdate builder.
func (bu *BlockUpdate) Where(ps ...predicate.Block) *BlockUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetSourceChainID sets the "SourceChainID" field.
func (bu *BlockUpdate) SetSourceChainID(u uint64) *BlockUpdate {
	bu.mutation.ResetSourceChainID()
	bu.mutation.SetSourceChainID(u)
	return bu
}

// SetNillableSourceChainID sets the "SourceChainID" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableSourceChainID(u *uint64) *BlockUpdate {
	if u != nil {
		bu.SetSourceChainID(*u)
	}
	return bu
}

// AddSourceChainID adds u to the "SourceChainID" field.
func (bu *BlockUpdate) AddSourceChainID(u int64) *BlockUpdate {
	bu.mutation.AddSourceChainID(u)
	return bu
}

// SetBlockHeight sets the "BlockHeight" field.
func (bu *BlockUpdate) SetBlockHeight(u uint64) *BlockUpdate {
	bu.mutation.ResetBlockHeight()
	bu.mutation.SetBlockHeight(u)
	return bu
}

// SetNillableBlockHeight sets the "BlockHeight" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableBlockHeight(u *uint64) *BlockUpdate {
	if u != nil {
		bu.SetBlockHeight(*u)
	}
	return bu
}

// AddBlockHeight adds u to the "BlockHeight" field.
func (bu *BlockUpdate) AddBlockHeight(u int64) *BlockUpdate {
	bu.mutation.AddBlockHeight(u)
	return bu
}

// SetBlockHash sets the "BlockHash" field.
func (bu *BlockUpdate) SetBlockHash(b []byte) *BlockUpdate {
	bu.mutation.SetBlockHash(b)
	return bu
}

// SetTimestamp sets the "Timestamp" field.
func (bu *BlockUpdate) SetTimestamp(t time.Time) *BlockUpdate {
	bu.mutation.SetTimestamp(t)
	return bu
}

// SetNillableTimestamp sets the "Timestamp" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableTimestamp(t *time.Time) *BlockUpdate {
	if t != nil {
		bu.SetTimestamp(*t)
	}
	return bu
}

// SetCreatedAt sets the "CreatedAt" field.
func (bu *BlockUpdate) SetCreatedAt(t time.Time) *BlockUpdate {
	bu.mutation.SetCreatedAt(t)
	return bu
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableCreatedAt(t *time.Time) *BlockUpdate {
	if t != nil {
		bu.SetCreatedAt(*t)
	}
	return bu
}

// AddMsgIDs adds the "Msgs" edge to the Msg entity by IDs.
func (bu *BlockUpdate) AddMsgIDs(ids ...int) *BlockUpdate {
	bu.mutation.AddMsgIDs(ids...)
	return bu
}

// AddMsgs adds the "Msgs" edges to the Msg entity.
func (bu *BlockUpdate) AddMsgs(m ...*Msg) *BlockUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return bu.AddMsgIDs(ids...)
}

// AddReceiptIDs adds the "Receipts" edge to the Receipt entity by IDs.
func (bu *BlockUpdate) AddReceiptIDs(ids ...int) *BlockUpdate {
	bu.mutation.AddReceiptIDs(ids...)
	return bu
}

// AddReceipts adds the "Receipts" edges to the Receipt entity.
func (bu *BlockUpdate) AddReceipts(r ...*Receipt) *BlockUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bu.AddReceiptIDs(ids...)
}

// Mutation returns the BlockMutation object of the builder.
func (bu *BlockUpdate) Mutation() *BlockMutation {
	return bu.mutation
}

// ClearMsgs clears all "Msgs" edges to the Msg entity.
func (bu *BlockUpdate) ClearMsgs() *BlockUpdate {
	bu.mutation.ClearMsgs()
	return bu
}

// RemoveMsgIDs removes the "Msgs" edge to Msg entities by IDs.
func (bu *BlockUpdate) RemoveMsgIDs(ids ...int) *BlockUpdate {
	bu.mutation.RemoveMsgIDs(ids...)
	return bu
}

// RemoveMsgs removes "Msgs" edges to Msg entities.
func (bu *BlockUpdate) RemoveMsgs(m ...*Msg) *BlockUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return bu.RemoveMsgIDs(ids...)
}

// ClearReceipts clears all "Receipts" edges to the Receipt entity.
func (bu *BlockUpdate) ClearReceipts() *BlockUpdate {
	bu.mutation.ClearReceipts()
	return bu
}

// RemoveReceiptIDs removes the "Receipts" edge to Receipt entities by IDs.
func (bu *BlockUpdate) RemoveReceiptIDs(ids ...int) *BlockUpdate {
	bu.mutation.RemoveReceiptIDs(ids...)
	return bu
}

// RemoveReceipts removes "Receipts" edges to Receipt entities.
func (bu *BlockUpdate) RemoveReceipts(r ...*Receipt) *BlockUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bu.RemoveReceiptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BlockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BlockUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BlockUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BlockUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BlockUpdate) check() error {
	if v, ok := bu.mutation.BlockHash(); ok {
		if err := block.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "BlockHash", err: fmt.Errorf(`ent: validator failed for field "Block.BlockHash": %w`, err)}
		}
	}
	return nil
}

func (bu *BlockUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(block.Table, block.Columns, sqlgraph.NewFieldSpec(block.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.SourceChainID(); ok {
		_spec.SetField(block.FieldSourceChainID, field.TypeUint64, value)
	}
	if value, ok := bu.mutation.AddedSourceChainID(); ok {
		_spec.AddField(block.FieldSourceChainID, field.TypeUint64, value)
	}
	if value, ok := bu.mutation.BlockHeight(); ok {
		_spec.SetField(block.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := bu.mutation.AddedBlockHeight(); ok {
		_spec.AddField(block.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := bu.mutation.BlockHash(); ok {
		_spec.SetField(block.FieldBlockHash, field.TypeBytes, value)
	}
	if value, ok := bu.mutation.Timestamp(); ok {
		_spec.SetField(block.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := bu.mutation.CreatedAt(); ok {
		_spec.SetField(block.FieldCreatedAt, field.TypeTime, value)
	}
	if bu.mutation.MsgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.MsgsTable,
			Columns: []string{block.MsgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msg.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedMsgsIDs(); len(nodes) > 0 && !bu.mutation.MsgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.MsgsTable,
			Columns: []string{block.MsgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.MsgsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.MsgsTable,
			Columns: []string{block.MsgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.ReceiptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.ReceiptsTable,
			Columns: []string{block.ReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedReceiptsIDs(); len(nodes) > 0 && !bu.mutation.ReceiptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.ReceiptsTable,
			Columns: []string{block.ReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.ReceiptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.ReceiptsTable,
			Columns: []string{block.ReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{block.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BlockUpdateOne is the builder for updating a single Block entity.
type BlockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlockMutation
}

// SetSourceChainID sets the "SourceChainID" field.
func (buo *BlockUpdateOne) SetSourceChainID(u uint64) *BlockUpdateOne {
	buo.mutation.ResetSourceChainID()
	buo.mutation.SetSourceChainID(u)
	return buo
}

// SetNillableSourceChainID sets the "SourceChainID" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableSourceChainID(u *uint64) *BlockUpdateOne {
	if u != nil {
		buo.SetSourceChainID(*u)
	}
	return buo
}

// AddSourceChainID adds u to the "SourceChainID" field.
func (buo *BlockUpdateOne) AddSourceChainID(u int64) *BlockUpdateOne {
	buo.mutation.AddSourceChainID(u)
	return buo
}

// SetBlockHeight sets the "BlockHeight" field.
func (buo *BlockUpdateOne) SetBlockHeight(u uint64) *BlockUpdateOne {
	buo.mutation.ResetBlockHeight()
	buo.mutation.SetBlockHeight(u)
	return buo
}

// SetNillableBlockHeight sets the "BlockHeight" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableBlockHeight(u *uint64) *BlockUpdateOne {
	if u != nil {
		buo.SetBlockHeight(*u)
	}
	return buo
}

// AddBlockHeight adds u to the "BlockHeight" field.
func (buo *BlockUpdateOne) AddBlockHeight(u int64) *BlockUpdateOne {
	buo.mutation.AddBlockHeight(u)
	return buo
}

// SetBlockHash sets the "BlockHash" field.
func (buo *BlockUpdateOne) SetBlockHash(b []byte) *BlockUpdateOne {
	buo.mutation.SetBlockHash(b)
	return buo
}

// SetTimestamp sets the "Timestamp" field.
func (buo *BlockUpdateOne) SetTimestamp(t time.Time) *BlockUpdateOne {
	buo.mutation.SetTimestamp(t)
	return buo
}

// SetNillableTimestamp sets the "Timestamp" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableTimestamp(t *time.Time) *BlockUpdateOne {
	if t != nil {
		buo.SetTimestamp(*t)
	}
	return buo
}

// SetCreatedAt sets the "CreatedAt" field.
func (buo *BlockUpdateOne) SetCreatedAt(t time.Time) *BlockUpdateOne {
	buo.mutation.SetCreatedAt(t)
	return buo
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableCreatedAt(t *time.Time) *BlockUpdateOne {
	if t != nil {
		buo.SetCreatedAt(*t)
	}
	return buo
}

// AddMsgIDs adds the "Msgs" edge to the Msg entity by IDs.
func (buo *BlockUpdateOne) AddMsgIDs(ids ...int) *BlockUpdateOne {
	buo.mutation.AddMsgIDs(ids...)
	return buo
}

// AddMsgs adds the "Msgs" edges to the Msg entity.
func (buo *BlockUpdateOne) AddMsgs(m ...*Msg) *BlockUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return buo.AddMsgIDs(ids...)
}

// AddReceiptIDs adds the "Receipts" edge to the Receipt entity by IDs.
func (buo *BlockUpdateOne) AddReceiptIDs(ids ...int) *BlockUpdateOne {
	buo.mutation.AddReceiptIDs(ids...)
	return buo
}

// AddReceipts adds the "Receipts" edges to the Receipt entity.
func (buo *BlockUpdateOne) AddReceipts(r ...*Receipt) *BlockUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return buo.AddReceiptIDs(ids...)
}

// Mutation returns the BlockMutation object of the builder.
func (buo *BlockUpdateOne) Mutation() *BlockMutation {
	return buo.mutation
}

// ClearMsgs clears all "Msgs" edges to the Msg entity.
func (buo *BlockUpdateOne) ClearMsgs() *BlockUpdateOne {
	buo.mutation.ClearMsgs()
	return buo
}

// RemoveMsgIDs removes the "Msgs" edge to Msg entities by IDs.
func (buo *BlockUpdateOne) RemoveMsgIDs(ids ...int) *BlockUpdateOne {
	buo.mutation.RemoveMsgIDs(ids...)
	return buo
}

// RemoveMsgs removes "Msgs" edges to Msg entities.
func (buo *BlockUpdateOne) RemoveMsgs(m ...*Msg) *BlockUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return buo.RemoveMsgIDs(ids...)
}

// ClearReceipts clears all "Receipts" edges to the Receipt entity.
func (buo *BlockUpdateOne) ClearReceipts() *BlockUpdateOne {
	buo.mutation.ClearReceipts()
	return buo
}

// RemoveReceiptIDs removes the "Receipts" edge to Receipt entities by IDs.
func (buo *BlockUpdateOne) RemoveReceiptIDs(ids ...int) *BlockUpdateOne {
	buo.mutation.RemoveReceiptIDs(ids...)
	return buo
}

// RemoveReceipts removes "Receipts" edges to Receipt entities.
func (buo *BlockUpdateOne) RemoveReceipts(r ...*Receipt) *BlockUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return buo.RemoveReceiptIDs(ids...)
}

// Where appends a list predicates to the BlockUpdate builder.
func (buo *BlockUpdateOne) Where(ps ...predicate.Block) *BlockUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BlockUpdateOne) Select(field string, fields ...string) *BlockUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Block entity.
func (buo *BlockUpdateOne) Save(ctx context.Context) (*Block, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BlockUpdateOne) SaveX(ctx context.Context) *Block {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BlockUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BlockUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BlockUpdateOne) check() error {
	if v, ok := buo.mutation.BlockHash(); ok {
		if err := block.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "BlockHash", err: fmt.Errorf(`ent: validator failed for field "Block.BlockHash": %w`, err)}
		}
	}
	return nil
}

func (buo *BlockUpdateOne) sqlSave(ctx context.Context) (_node *Block, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(block.Table, block.Columns, sqlgraph.NewFieldSpec(block.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Block.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, block.FieldID)
		for _, f := range fields {
			if !block.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != block.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.SourceChainID(); ok {
		_spec.SetField(block.FieldSourceChainID, field.TypeUint64, value)
	}
	if value, ok := buo.mutation.AddedSourceChainID(); ok {
		_spec.AddField(block.FieldSourceChainID, field.TypeUint64, value)
	}
	if value, ok := buo.mutation.BlockHeight(); ok {
		_spec.SetField(block.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := buo.mutation.AddedBlockHeight(); ok {
		_spec.AddField(block.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := buo.mutation.BlockHash(); ok {
		_spec.SetField(block.FieldBlockHash, field.TypeBytes, value)
	}
	if value, ok := buo.mutation.Timestamp(); ok {
		_spec.SetField(block.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := buo.mutation.CreatedAt(); ok {
		_spec.SetField(block.FieldCreatedAt, field.TypeTime, value)
	}
	if buo.mutation.MsgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.MsgsTable,
			Columns: []string{block.MsgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msg.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedMsgsIDs(); len(nodes) > 0 && !buo.mutation.MsgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.MsgsTable,
			Columns: []string{block.MsgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.MsgsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.MsgsTable,
			Columns: []string{block.MsgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.ReceiptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.ReceiptsTable,
			Columns: []string{block.ReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedReceiptsIDs(); len(nodes) > 0 && !buo.mutation.ReceiptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.ReceiptsTable,
			Columns: []string{block.ReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.ReceiptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   block.ReceiptsTable,
			Columns: []string{block.ReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(receipt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Block{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{block.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
