version: 2

project_name: trade

# Only linux/amd64 docker images are needed

builds:
  - id: trade
    main: .
    binary: trade
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]

dockers:
  - ids: [ trade ]
    dockerfile: ./Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - omniops/trade:{{ .ShortCommit }}
      - omniops/trade:main

release:
  disable: true

changelog:
  disable: true
