blank_issues_enabled: true
contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/orgs/omni-network/discussions"
    about: "Make sure to also give our GitHub Discussions site a look too."
