name: Setup Foundry
description: Install the foundry toolchain

inputs:
  docker:
    description: "Whether or not to pull foundry docker image"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Get foundry version
      id: foundry_version
      shell: bash
      run: echo "version=$(cat scripts/foundry_version.txt)" >> $GITHUB_OUTPUT

    - name: Install toolchain
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ steps.foundry_version.outputs.version }}

    - name: Install docker
      shell: bash
      if: ${{ inputs.docker == 'true' }}
      run: docker pull ghcr.io/foundry-rs/foundry:${{ steps.foundry_version.outputs.version}}
