// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: lib/cctp/db/db.proto

package db

import (
	_ "cosmossdk.io/api/cosmos/orm/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgSendUSDC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHash   []byte                 `protobuf:"bytes,1,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	TxHash        []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	SrcChainId    uint64                 `protobuf:"varint,3,opt,name=src_chain_id,json=srcChainId,proto3" json:"src_chain_id,omitempty"`
	DestChainId   uint64                 `protobuf:"varint,4,opt,name=dest_chain_id,json=destChainId,proto3" json:"dest_chain_id,omitempty"`
	Amount        []byte                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	MessageBytes  []byte                 `protobuf:"bytes,6,opt,name=message_bytes,json=messageBytes,proto3" json:"message_bytes,omitempty"`
	Recipient     []byte                 `protobuf:"bytes,7,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSendUSDC) Reset() {
	*x = MsgSendUSDC{}
	mi := &file_lib_cctp_db_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSendUSDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendUSDC) ProtoMessage() {}

func (x *MsgSendUSDC) ProtoReflect() protoreflect.Message {
	mi := &file_lib_cctp_db_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendUSDC.ProtoReflect.Descriptor instead.
func (*MsgSendUSDC) Descriptor() ([]byte, []int) {
	return file_lib_cctp_db_db_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSendUSDC) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *MsgSendUSDC) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *MsgSendUSDC) GetSrcChainId() uint64 {
	if x != nil {
		return x.SrcChainId
	}
	return 0
}

func (x *MsgSendUSDC) GetDestChainId() uint64 {
	if x != nil {
		return x.DestChainId
	}
	return 0
}

func (x *MsgSendUSDC) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MsgSendUSDC) GetMessageBytes() []byte {
	if x != nil {
		return x.MessageBytes
	}
	return nil
}

func (x *MsgSendUSDC) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_lib_cctp_db_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_lib_cctp_db_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_lib_cctp_db_db_proto_rawDescGZIP(), []int{1}
}

func (x *Cursor) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Cursor) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

var File_lib_cctp_db_db_proto protoreflect.FileDescriptor

const file_lib_cctp_db_db_proto_rawDesc = "" +
	"\n" +
	"\x14lib/cctp/db/db.proto\x12\vlib.cctp.db\x1a\x17cosmos/orm/v1/orm.proto\"\x84\x02\n" +
	"\vMsgSendUSDC\x12!\n" +
	"\fmessage_hash\x18\x01 \x01(\fR\vmessageHash\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12 \n" +
	"\fsrc_chain_id\x18\x03 \x01(\x04R\n" +
	"srcChainId\x12\"\n" +
	"\rdest_chain_id\x18\x04 \x01(\x04R\vdestChainId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\fR\x06amount\x12#\n" +
	"\rmessage_bytes\x18\x06 \x01(\fR\fmessageBytes\x12\x1c\n" +
	"\trecipient\x18\a \x01(\fR\trecipient:\x18\xf2\x9eӎ\x03\x12\n" +
	"\x0e\n" +
	"\fmessage_hash\x18\x01\"\\\n" +
	"\x06Cursor\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight:\x14\xf2\x9eӎ\x03\x0e\n" +
	"\n" +
	"\n" +
	"\bchain_id\x18\x02B\x92\x01\n" +
	"\x0fcom.lib.cctp.dbB\aDbProtoP\x01Z(github.com/omni-network/omni/lib/cctp/db\xa2\x02\x03LCD\xaa\x02\vLib.Cctp.Db\xca\x02\vLib\\Cctp\\Db\xe2\x02\x17Lib\\Cctp\\Db\\GPBMetadata\xea\x02\rLib::Cctp::Dbb\x06proto3"

var (
	file_lib_cctp_db_db_proto_rawDescOnce sync.Once
	file_lib_cctp_db_db_proto_rawDescData []byte
)

func file_lib_cctp_db_db_proto_rawDescGZIP() []byte {
	file_lib_cctp_db_db_proto_rawDescOnce.Do(func() {
		file_lib_cctp_db_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_cctp_db_db_proto_rawDesc), len(file_lib_cctp_db_db_proto_rawDesc)))
	})
	return file_lib_cctp_db_db_proto_rawDescData
}

var file_lib_cctp_db_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_cctp_db_db_proto_goTypes = []any{
	(*MsgSendUSDC)(nil), // 0: lib.cctp.db.MsgSendUSDC
	(*Cursor)(nil),      // 1: lib.cctp.db.Cursor
}
var file_lib_cctp_db_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_cctp_db_db_proto_init() }
func file_lib_cctp_db_db_proto_init() {
	if File_lib_cctp_db_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_cctp_db_db_proto_rawDesc), len(file_lib_cctp_db_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_cctp_db_db_proto_goTypes,
		DependencyIndexes: file_lib_cctp_db_db_proto_depIdxs,
		MessageInfos:      file_lib_cctp_db_db_proto_msgTypes,
	}.Build()
	File_lib_cctp_db_db_proto = out.File
	file_lib_cctp_db_db_proto_goTypes = nil
	file_lib_cctp_db_db_proto_depIdxs = nil
}
