[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.22"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solver_inbox = "AwminMpVyPSX86m3w9KWcxjovtnjwxiKZUNTDgDqrctv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./localnet/solver_inbox-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
