// Code generated by "stringer -type=RejectReason -trimprefix=Reject"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RejectNone-0]
	_ = x[RejectDestCallReverts-1]
	_ = x[RejectInvalidDeposit-2]
	_ = x[RejectInvalidExpense-3]
	_ = x[RejectInsufficientDeposit-4]
	_ = x[RejectInsufficientInventory-5]
	_ = x[RejectUnsupportedDeposit-6]
	_ = x[RejectUnsupportedExpense-7]
	_ = x[RejectUnsupportedDestChain-8]
	_ = x[RejectUnsupportedSrcChain-9]
	_ = x[RejectSameChain-10]
	_ = x[RejectExpenseOverMax-11]
	_ = x[RejectExpenseUnderMin-12]
}

const _RejectReason_name = "NoneDestCallRevertsInvalidDepositInvalidExpenseInsufficientDepositInsufficientInventoryUnsupportedDepositUnsupportedExpenseUnsupportedDestChainUnsupportedSrcChainSameChainExpenseOverMaxExpenseUnderMin"

var _RejectReason_index = [...]uint8{0, 4, 19, 33, 47, 66, 87, 105, 123, 143, 162, 171, 185, 200}

func (i RejectReason) String() string {
	if i >= RejectReason(len(_RejectReason_index)-1) {
		return "RejectReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RejectReason_name[_RejectReason_index[i]:_RejectReason_index[i+1]]
}
