// Code generated by ent, DO NOT EDIT.

package receipt

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the receipt type in the database.
	Label = "receipt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldBlockID holds the string denoting the block_id field in the database.
	FieldBlockID = "block_id"
	// FieldGasUsed holds the string denoting the gasused field in the database.
	FieldGasUsed = "gas_used"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldRelayerAddress holds the string denoting the relayeraddress field in the database.
	FieldRelayerAddress = "relayer_address"
	// FieldSourceChainID holds the string denoting the sourcechainid field in the database.
	FieldSourceChainID = "source_chain_id"
	// FieldDestChainID holds the string denoting the destchainid field in the database.
	FieldDestChainID = "dest_chain_id"
	// FieldStreamOffset holds the string denoting the streamoffset field in the database.
	FieldStreamOffset = "stream_offset"
	// FieldTxHash holds the string denoting the txhash field in the database.
	FieldTxHash = "tx_hash"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// EdgeBlock holds the string denoting the block edge name in mutations.
	EdgeBlock = "Block"
	// EdgeMsgs holds the string denoting the msgs edge name in mutations.
	EdgeMsgs = "Msgs"
	// Table holds the table name of the receipt in the database.
	Table = "receipts"
	// BlockTable is the table that holds the Block relation/edge.
	BlockTable = "receipts"
	// BlockInverseTable is the table name for the Block entity.
	// It exists in this package in order to avoid circular dependency with the "block" package.
	BlockInverseTable = "blocks"
	// BlockColumn is the table column denoting the Block relation/edge.
	BlockColumn = "block_id"
	// MsgsTable is the table that holds the Msgs relation/edge. The primary key declared below.
	MsgsTable = "msg_Receipts"
	// MsgsInverseTable is the table name for the Msg entity.
	// It exists in this package in order to avoid circular dependency with the "msg" package.
	MsgsInverseTable = "msgs"
)

// Columns holds all SQL columns for receipt fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldBlockID,
	FieldGasUsed,
	FieldSuccess,
	FieldRelayerAddress,
	FieldSourceChainID,
	FieldDestChainID,
	FieldStreamOffset,
	FieldTxHash,
	FieldCreatedAt,
}

var (
	// MsgsPrimaryKey and MsgsColumn2 are the table columns denoting the
	// primary key for the Msgs relation (M2M).
	MsgsPrimaryKey = []string{"msg_id", "receipt_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/omni-network/omni/explorer/db/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultUUID holds the default value on creation for the "UUID" field.
	DefaultUUID func() uuid.UUID
	// RelayerAddressValidator is a validator for the "RelayerAddress" field. It is called by the builders before save.
	RelayerAddressValidator func([]byte) error
	// TxHashValidator is a validator for the "TxHash" field. It is called by the builders before save.
	TxHashValidator func([]byte) error
	// DefaultCreatedAt holds the default value on creation for the "CreatedAt" field.
	DefaultCreatedAt time.Time
)

// OrderOption defines the ordering options for the Receipt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUUID orders the results by the UUID field.
func ByUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByBlockID orders the results by the Block_ID field.
func ByBlockID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockID, opts...).ToFunc()
}

// ByGasUsed orders the results by the GasUsed field.
func ByGasUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGasUsed, opts...).ToFunc()
}

// BySuccess orders the results by the Success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// BySourceChainID orders the results by the SourceChainID field.
func BySourceChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceChainID, opts...).ToFunc()
}

// ByDestChainID orders the results by the DestChainID field.
func ByDestChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestChainID, opts...).ToFunc()
}

// ByStreamOffset orders the results by the StreamOffset field.
func ByStreamOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamOffset, opts...).ToFunc()
}

// ByCreatedAt orders the results by the CreatedAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByBlockField orders the results by Block field.
func ByBlockField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlockStep(), sql.OrderByField(field, opts...))
	}
}

// ByMsgsCount orders the results by Msgs count.
func ByMsgsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMsgsStep(), opts...)
	}
}

// ByMsgs orders the results by Msgs terms.
func ByMsgs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMsgsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBlockStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlockInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlockTable, BlockColumn),
	)
}
func newMsgsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MsgsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, MsgsTable, MsgsPrimaryKey...),
	)
}
