# Backwards ensures backwards-compatibility with v0.13.0 (the first version supporting magellan)
network = "devnet"
anvil_chains = ["mock_l1", "mock_l2"]

multi_omni_evms = true

[node.validator01]
[node.validator02]
mode = "archive"

[node.validator03]
version="omniops/halovisor:v0.13.0"
perturb = ["upgrade"]

[node.validator04]
version="omniops/halovisor:v0.13.0"
perturb = ["upgrade"]

[perturb]
validator01_evm = ["upgrade"]
validator02_evm = ["upgrade"]
validator03_evm = ["upgrade"]
validator04_evm = ["upgrade"]
