network = "testnet"

public_chains = ["holesky","op_sepolia","arb_sepolia"]
avs_target = "holesky"

multi_omni_evms = true
prometheus = true
explorer = true

[node.validator01]
[node.validator02]
[node.validator03]
[node.validator04]

[node.seed01]
mode = "seed"
[node.seed02]
mode = "seed"

[node.fullnode01]
mode = "full"
[node.fullnode02]
mode = "full"
[node.fullnode03]
mode = "full"
[node.fullnode04]
mode = "full"
[node.fullnode05]
mode = "full"

[node.archive01]
mode = "archive"


[keys.validator01]
validator = "0x5e7B5b243824E15796c33a8829F7807F2C5EeDc0"

[keys.validator02]
validator = "0xD10A6A65C5586aF6093A4F993C3d609758c2a32b"

[keys.validator03]
validator = "0xf64deF685fF01761D7b5D58452016D0dC9fa43eF"

[keys.validator04]
validator = "0x34E0afB2FC3f43D469d9C07436c1A885A0979922"

[keys.seed01]
p2p_consensus = "9644D22FCC9D3966CFF5789E6C411FDD40B101ED"

[keys.seed01_evm]
p2p_execution = "0xA49cdBbFfF2fD0a3bD5a5780b5a4eB717A3D2c00"

[keys.seed02]
p2p_consensus = "A839711D734491E1BA99A69E3FEEEBB965223792"

[keys.seed02_evm]
p2p_execution = "0xf6d3676305dBf0Ba4BC97ad17833792dE6dC4AB7"
