version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: explorer_db
    environment:
      POSTGRES_DB: omni_db
      POSTGRES_USER: omni
      POSTGRES_PASSWORD: password
      ports: 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U omni -d omni_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  graphql:
    image: omniops/explorer-graphql:main
    environment:
      - GRAPHQL_LOG_COLOR=force
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  indexer:
    image: omniops/explorer-indexer:main
    environment:
      - INDEXER_LOG_COLOR=force
    volumes:
      - ./network.json:/network.json
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    name: devnet1_devnet1
    external: true
