/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  type Codec,
  type Decoder,
  type Encoder,
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
} from '@solana/kit'

export enum Status {
  Invalid = 0,
  Pending = 1,
  Rejected = 2,
  Closed = 3,
  Filled = 4,
  Claimed = 5,
}

export type StatusArgs = Status

export function getStatusEncoder(): Encoder<StatusArgs> {
  return getEnumEncoder(Status)
}

export function getStatusDecoder(): Decoder<Status> {
  return getEnumDecoder(Status)
}

export function getStatusCodec(): Codec<StatusArgs, Status> {
  return combineCodec(getStatusEncoder(), getStatusDecoder())
}
