name: Changesets

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

# restrict to a single instance of this workflow per git ref and cancel existing in-progress
# runs to prevent race conditions when bumping versions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  sdk-version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # fetches entire git history for changesets to generate changelogs considering the correct commits
          fetch-depth: 0

      - name: Check for SDK changes
        id: sdk_changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            sdk/**

      - name: Setup pnpm
        if: steps.sdk_changes.outputs.any_changed == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node.js
        if: steps.sdk_changes.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        if: steps.sdk_changes.outputs.any_changed == 'true'
        working-directory: sdk
        run: pnpm install

      - name: Bump versions
        if: steps.sdk_changes.outputs.any_changed == 'true'
        uses: changesets/action@v1
        with:
          commit: "chore(sdk): bump versions"
          title: "chore(sdk): bump versions"
          version: "pnpm changeset:version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log no SDK changes
        if: steps.sdk_changes.outputs.any_changed != 'true'
        run: echo "No changes in the sdk/ directory - skipping version bump..."
