name: ci release
# continuous integration on git tagged release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-official:
    uses: ./.github/workflows/release-official.yml
    secrets: inherit
