name: e2e tests

on:
  workflow_call:

jobs:
  e2e_tests:
    runs-on: namespace-profile-default
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run e2e tests
        run: make e2e-ci
      - name: Upload failed logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failed-logs
          path: e2e/failed-logs.txt
          retention-days: 3

      - name: e2e-logs
        if: failure()
        uses: metrico/loki-action@V3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          endpoint: ${{ secrets.LOGQL_ENDPOINT }}
          username: ${{ secrets.LOGQL_USER }}
          password: ${{ secrets.LOGQL_PASS }}
