name: Go

on:
  push:
    branches: [main]
  pull_requests:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod
      - name: Test with race detector
        run: make test-race
