name: go lint
# Run this separately from pre-commit since then we get nice inline messages in PRs.

on:
  workflow_call:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          # Verbose with color. Just fail, don't fix issues. Use both annotations and normal output.
          args: -v --color=always --fix=false --out-format=colored-line-number,github-actions
