name: Publish Docker Images

# Run on all commits to main
on:
  push:
    branches:
      - main

# TODO(corver): Figure out which images to publish and how to do this via goreleaser.

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Login to Dockerhub container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker images
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          # Use --snapshot to build current HEAD commit (this doesn't publish images)
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Dockerhub
        run: docker push omniops/halo:latest
