name: go tests
# Run this separately from pre-commit for nice visual coverage.

on:
  workflow_call:

jobs:
  unit_tests:
    runs-on: namespace-profile-default
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      # TODO(corver): add coverage
      - name: Pull anvil # This can be slow and cause timeouts
        run: docker pull ghcr.io/foundry-rs/foundry:latest
      - run: go test -timeout=5m -race -tags=verify_logs ./...
