name: release official
# Official releases on tagged commits.

on:
  workflow_call:

jobs:
  release-official:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker images
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 2
          args: release -f .goreleaser-official.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push halovisor
        uses: docker/build-push-action@v6
        with:
          file: scripts/halovisor/Dockerfile
          build-args: |
            HALO_VERSION_1_ULUWATU=${{ github.ref_name }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            omniops/halovisor:latest
            omniops/halovisor:${{ github.ref_name }}
