name: solidity tests
# Run this separately from pre-commit for nice visual coverage.

on:
  workflow_call:

jobs:
  sol_core_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/core
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-foundry
      - name: Install pnpm
        run: make install-pnpm
        working-directory: contracts
      - run: pnpm install
      - name: Check fmt
        run: forge fmt --check
      - name: Run tests
        run: forge test -vv
      - name: Check snapshot
        # fuzz tests snapshots are different in CI, so we ignore them
        run: forge snapshot --check --tolerance 5
        env:
            FOUNDRY_FUZZ_SEED: "0x6eed"

  sol_avs_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/avs
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-foundry
      - name: Install pnpm
        run: make install-pnpm
        working-directory: contracts
      - run: pnpm install
      - name: Check fmt
        run: forge fmt --check
      - name: Run tests
        run: forge test -vv
      - name: Check snapshot
        # fuzz tests snapshots are different in CI, so we ignore them
        run: forge snapshot --check --tolerance 5 --no-match-test testFuzz_syncWithOmni
        env:
            FOUNDRY_FUZZ_SEED: "0x6eed"

  sol_solve_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/solve
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-foundry
      - name: Install pnpm
        run: make install-pnpm
        working-directory: contracts
      - run: pnpm install
      - name: Check fmt
        run: forge fmt --check
      - name: Run tests
        run: forge test -vv
      - name: Check snapshot
        # fuzz tests snapshots are different in CI, so we ignore them
        run: forge snapshot --check --tolerance 5
        env:
            FOUNDRY_FUZZ_SEED: "0x6eed"

  sol_nomina_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts/nomina
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-foundry
      - name: Install pnpm
        run: make install-pnpm
        working-directory: contracts
      - run: pnpm install
      - name: Check fmt
        run: forge fmt --check
      - name: Run tests
        run: forge test -vv
      - name: Check snapshot
        # fuzz tests snapshots are different in CI, so we ignore them
        run: forge snapshot --check --tolerance 5
        env:
            FOUNDRY_FUZZ_SEED: "0x6eed"
