name: verifypr
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      GITHUB_PR: ${{ toJSON(github.event.pull_request) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: "Verify PR"
        run: go run github.com/omni-network/omni/scripts/verifypr
